--[[
-- Orca, a free and open-source Roblox script hub.
-- This script was generated by ci/bundle.lua, and is not intended to be modified.
-- To view the source code, see the 'src' folder on GitHub!
--
-- Author: taco
-- License: MIT
-- Version: __VERSION__
-- GitHub: https://github.com/mgtaco/orcaplus
--]]

-- Persist this custom build across reconnects / server hops.
--
-- If your executor supports script.Source this happens automatically.
-- Otherwise, add ONE line before running orca (e.g. in autoexec):
--
--   getgenv()._ORCA_RELOAD = 'loadstring(readfile("path/to/orca.lua"))()'
--
-- Orca will queue that string instead of fetching from GitHub.
do
	-- Only auto-set _ORCA_RELOAD when the user has not already specified one.
	local g = type(getgenv) == "function" and getgenv() or nil
	if g and not g._ORCA_RELOAD then
		local ok, src = pcall(function() return script.Source end)
		if ok and type(src) == "string" and #src > 1000 then
			-- Source looks valid — save to disk and mark the reload path.
			pcall(function()
				if not isfolder("_orca") then
					makefolder("_orca")
				end
				writefile("_orca/reload.lua", src)
				g._ORCA_RELOAD = 'loadstring(readfile("_orca/reload.lua"))()'
			end)
		end
	end
end

-- Runtime module

---@class Module
---@field fn function
---@field isLoaded boolean
---@field value any

---@type table<string, Instance>
local instanceFromId = {}

---@type table<Instance, string>
local idFromInstance = {}

---@type table<Instance, Module>
local modules = {}

---Stores currently loading modules.
---@type table<LocalScript | ModuleScript, ModuleScript>
local currentlyLoading = {}

local function getOrcaGlobal()
	local ok, genv = pcall(function()
		return getgenv and getgenv()
	end)
	if ok then
		return genv
	end
end

local function setOrcaRoot(instance, path)
	if path ~= "Orca" then
		return
	end

	local g = getOrcaGlobal()
	if not g then
		return
	end

	if g._ORCA_ROOT and not g._ORCA_SESSION then
		pcall(function()
			g._ORCA_ROOT:Destroy()
		end)
	end
	g._ORCA_ROOT = instance
end

-- Module resolution

---@param module LocalScript | ModuleScript
---@param caller? LocalScript | ModuleScript
---@return function | nil cleanup
local function validateRequire(module, caller)
	currentlyLoading[caller] = module

	local currentModule = module
	local depth = 0

	-- If the module is loaded, requiring it will not cause a circular dependency.
	if not modules[module] then
		while currentModule do
			depth = depth + 1
			currentModule = currentlyLoading[currentModule]

			if currentModule == module then
				local str = currentModule.Name -- Get the string traceback

				for _ = 1, depth do
					currentModule = currentlyLoading[currentModule]
					str = str .. "  ⇒ " .. currentModule.Name
				end

				error("Failed to load '" .. module.Name .. "'; Detected a circular dependency chain: " .. str, 2)
			end
		end
	end

	return function ()
		if currentlyLoading[caller] == module then -- Thread-safe cleanup!
			currentlyLoading[caller] = nil
		end
	end
end

---@param obj LocalScript | ModuleScript
---@param this? LocalScript | ModuleScript
---@return any
local function loadModule(obj, this)
	local cleanup = this and validateRequire(obj, this)
	local module = modules[obj]

	if module.isLoaded then
		if cleanup then
			cleanup()
		end
		return module.value
	else
		local data = module.fn()
		module.value = data
		module.isLoaded = true
		if cleanup then
			cleanup()
		end
		return data
	end
end

---@param target ModuleScript
---@param this? LocalScript | ModuleScript
---@return any
local function requireModuleInternal(target, this)
	if modules[target] and target:IsA("ModuleScript") then
		return loadModule(target, this)
	else
		return require(target)
	end
end

-- Instance creation

---@param id string
---@return table<string, any> environment
local function newEnv(id)
	return setmetatable({
		VERSION = __VERSION__,
		script = instanceFromId[id],
		require = function (module)
			return requireModuleInternal(module, instanceFromId[id])
		end,
	}, {
		__index = getfenv(0),
		__metatable = "This metatable is locked",
	})
end

---@param name string
---@param className string
---@param path string
---@param parent string | nil
---@param fn function
local function newModule(name, className, path, parent, fn)
	local instance = Instance.new(className)
	instance.Name = name
	instance.Parent = instanceFromId[parent]

	instanceFromId[path] = instance
	idFromInstance[instance] = path
	setOrcaRoot(instance, path)

	modules[instance] = {
		fn = fn,
		isLoaded = false,
		value = nil,
	}
end

---@param name string
---@param className string
---@param path string
---@param parent string | nil
local function newInstance(name, className, path, parent)
	local instance = Instance.new(className)
	instance.Name = name
	instance.Parent = instanceFromId[parent]

	instanceFromId[path] = instance
	idFromInstance[instance] = path
	setOrcaRoot(instance, path)
end

-- Runtime

local function init()
	if not game:IsLoaded() then
		game.Loaded:Wait()
	end
	for object in pairs(modules) do
		if object:IsA("LocalScript") and not object.Disabled then
			task.spawn(loadModule, object)
		end
	end
end
